- name: generate configs
  hosts: all
  gather_facts: false
  
  tasks:

     - name: Ansible config generation
       template: 
           src: small_sku_template.j2
           dest: "{{ inventory_hostname }}.txt"
          