---
- name: Template Looping
  hosts: localhost
  
  vars:
    nexus_devices: {
      "SW3": {
        "hostname": "SW3",
        "username": "cisco",
        "password": "cisco",
        "vlans": [100, 200, 300],
        "l3_vlan_interfaces": True,
        "vlan_interfaces": [
          {"int_num": "100", "ip": "192.168.1.6"},
          {"int_num": "200", "ip": "192.168.2.6"},
          {"int_num": "300", "ip": "192.168.3.6"}
        ],
        "netflow_enable": True
      },
      "SW4": {
        "hostname": "SW4",
        "username": "cisco",
        "password": "cisco",
        "vlans": [100, 200, 300],
        "l3_vlan_interfaces": False,
        "netflow_enable": False
      }
    }

  tasks:
    - name: create nexus switch configuration files
      with_dict: "{{ nexus_devices }}"
      template:
        src: nxos.j2
        dest: "{{ item.key }}.conf"