---
- name: IOS command output for when clause
  hosts: ios-devices
  gather_facts: false
  tasks:
    - name: show hostname
      ios_command:
        commands:
          - show run | i hostname
      register: output

    - name: show output with when conditions
      when: output.stdout == ["hostname R1"]
      # when: ansible_network_os == 'ios'
      debug:
        msg: '{{ output }}'